USE BD_SPIRITUAL_ART
--PROCEDIMIENTOS ALMACENADOS SPIRITUAL ART

--REGISTRA ARTISTA Y GENERA CONTRASEÑA AL AZAR Y EL ESTADO AUTOMÁTICAMENTE
ALTER PROCEDURE SP_REGISTRAR_ARTISTA
@NOMBRE_ARTISTA VARCHAR(50),
@PRIMER_APELLIDO_ARTISTA VARCHAR(50),
@SEGUNDO_APELLIDO_ARTISTA VARCHAR(50),
@TELEFONO VARCHAR(30),
@CORREO VARCHAR(40),
@PAIS VARCHAR(30),
@CIUDAD VARCHAR(30),
@LOCALIDAD VARCHAR(50),
@DIRECCION VARCHAR(50),
@FK_TIPO_PLAN INT,
@CLAVE varchar(20),
@ESTADO BIT,
@IMAGEN VARCHAR(MAX)
AS
BEGIN

SET @CLAVE = ABS(CHECKSUM(NEWID()))% 900000
SET @ESTADO = 1
INSERT INTO REGISTRO_ARTISTA(NOMBRE_ARTISTA,PRIMER_APELLIDO_ARTISTA,SEGUNDO_APELLIDO_ARTISTA,TELEFONO,CORREO,PAIS,CIUDAD,LOCALIDAD,DIRECCION,CLAVE,FK_TIPO_PLAN,ESTADO,IMAGEN)
VALUES(@NOMBRE_ARTISTA,@PRIMER_APELLIDO_ARTISTA,@SEGUNDO_APELLIDO_ARTISTA,@TELEFONO,@CORREO,@PAIS,@CIUDAD,@LOCALIDAD,@DIRECCION,@CLAVE,@FK_TIPO_PLAN,@ESTADO,@IMAGEN)
END

EXEC SP_REGISTRAR_ARTISTA 'Luisa','López','Toro','3197564392','lufelopez223@outlook.com','Colombia','Medellín','Antioquia','carrera 80',10,''

--REGISTRA CLIENTE E INGRESA DATOS A LA TABLA NOTIFICACIONES AUTOMÁTICAMENTE

ALTER PROCEDURE SP_REGISTRO_CLIENTE
@NOMBRE_CLIENTE VARCHAR(50),
@APELLIDO_CLIENTE VARCHAR(50),
@TELEFONO_CLIENTE VARCHAR(30),
@EMAIL_CLIENTE VARCHAR(40),
@ASUNTO VARCHAR(100),
@MENSAJE VARCHAR(500),
@FK_ARTISTA INT,
@FK_PRODUCTO INT
AS
BEGIN

DECLARE @FK_CLIENTE INT
 

INSERT INTO CLIENTE(NOMBRE_CLIENTE,APELLIDO_CLIENTE,TELEFONO_CLIENTE,EMAIL_CLIENTE,ASUNTO,MENSAJE)
VALUES(@NOMBRE_CLIENTE,@APELLIDO_CLIENTE,@TELEFONO_CLIENTE,@EMAIL_CLIENTE,@ASUNTO,@MENSAJE)

SET @FK_CLIENTE = SCOPE_IDENTITY()

EXEC SP_REGISTRAR_NOTIFICACION @FK_CLIENTE,@FK_ARTISTA,@FK_PRODUCTO

END

ALTER PROCEDURE SP_REGISTRAR_NOTIFICACION
@FK_CLIENTE INT,
@FK_ARTISTA INT,
@FK_PRODUCTO INT
AS
BEGIN
DECLARE @FECHA DATE
SET @FECHA = GETDATE()

INSERT INTO NOTIFICACION(FECHA,FK_ARTISTA,FK_CLIENTE,FK_PRODUCTO) VALUES(@FECHA,@FK_ARTISTA,@FK_CLIENTE,@FK_PRODUCTO)
END

EXEC SP_REGISTRO_CLIENTE 'CLIENTE TEST2','APELLIDO TEST2','3195665512','CORREOTEST2@GMAIL.COM','INTERESADO EN EL CUADRO','COMO CONSIGO ESTE CUADRO',47


declare @clave varchar(20)
set @clave = ABS(CHECKSUM(NEWID()))% 900000
print @clave
